# 机床生产利润问题

In [4]:
# 导库
from scipy import optimize
import numpy as np

# 目标函数
c = np.array([4,3]) 

#不等式约束
A = np.array([[2,1],[1,1],[0,1]])
b = np.array([10,8,7])

# 上下界约束
lb = [0, 0]
ub = [None, None]
bounds = np.array(list(zip(lb, ub)))

# 求解
result = optimize.linprog(-c, A, b, None, None, bounds)
x=result.x
zmax=-result.fun
print(f"最优解:{x}\n最优值:{zmax}")

最优解:[2. 6.]
最优值:25.99999999984096


In [15]:
# 导库
import pulp
import numpy as np

# 初始化线性规划问题模型
pro = pulp.LpProblem(sense=pulp.LpMaximize)

# 创建决策变量
x1=pulp.LpVariable('x1',lowBound=0)
x2=pulp.LpVariable('x2',lowBound=0)

#建立目标函数
pro+=4*x1+3*x2

# 不等式约束
pro+= (2*x1+x2<=10)
pro+= (x1+x2<=8)
pro+= (x2<=7)

#求解
pro.solve()

#输出结果
print(pro)
print(f'最优值：{pulp.value(pro.objective)}')
print(f'最优解：[{pulp.value(x1)},{pulp.value(x2)}]')

NoName:
MAXIMIZE
4*x1 + 3*x2 + 0
SUBJECT TO
_C1: 2 x1 + x2 <= 10

_C2: x1 + x2 <= 8

_C3: x2 <= 7

VARIABLES
x1 Continuous
x2 Continuous

最优值：26.0
最优解：[2.0,6.0]


# 仓库租借问题

In [44]:
# 导库
import pulp
import numpy as np

# 初始化线性规划问题模型
pro = pulp.LpProblem(sense=pulp.LpMinimize)

# 创建决策变量
x = []
for i in range(1, 5):
    x.append([pulp.LpVariable(f"x_{i}{j}", lowBound=0) for j in range(1, 5)])
x = np.array(x)

#建立目标函数
pro += 2800 * np.sum(x[:, 0]) + 4500 * np.sum(x[0:3, 1]) + 6000 * np.sum(
    x[0:2, 2]) + 7300 * x[0, 3]

# 不等式约束
pro += np.sum(x[0, :]) >= 15
pro += np.sum(x[0, 1:4]) + np.sum(x[1, 1:4]) >= 10
pro += np.sum(x[0, 2:4]) + np.sum(x[1, 1:3]) + np.sum(x[2, 0:2]) >= 20
pro += x[0, 3] + x[1, 2] + x[2, 1] + x[3, 0] >= 12

#求解
pro.solve()

#输出结果
print(pro)
print(f'最优值：{pulp.value(pro.objective)}')
for i in range(4):
    for j in range(4):
        x[i, j] = pulp.value(x[i, j])
x[x == None] = 0
print(f'最优解:\n{x}')

NoName:
MINIMIZE
2800*x_11 + 4500*x_12 + 6000*x_13 + 7300*x_14 + 2800*x_21 + 4500*x_22 + 6000*x_23 + 2800*x_31 + 4500*x_32 + 2800*x_41 + 0
SUBJECT TO
_C1: x_11 + x_12 + x_13 + x_14 >= 15

_C2: x_12 + x_13 + x_14 + x_22 + x_23 + x_24 >= 10

_C3: x_13 + x_14 + x_22 + x_23 + x_31 + x_32 >= 20

_C4: x_14 + x_23 + x_32 + x_41 >= 12

VARIABLES
x_11 Continuous
x_12 Continuous
x_13 Continuous
x_14 Continuous
x_21 Continuous
x_22 Continuous
x_23 Continuous
x_24 Continuous
x_31 Continuous
x_32 Continuous
x_41 Continuous

最优值：118400.0
最优解:
[[3.0 0.0 0.0 12.0]
 [0.0 0.0 0.0 0.0]
 [8.0 0.0 0 0]
 [0.0 0 0 0]]
